{{- if and .Values.apiKey.enabled .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pseudonymizer.fullname" . }}-apikey
  labels:
    {{- include "pseudonymizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey.value | quote }}
{{- end }}
{{- if and .Values.deterministic.enabled .Values.deterministic.value (not .Values.deterministic.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pseudonymizer.fullname" . }}-deterministic
  labels:
    {{- include "pseudonymizer.labels" . | nindent 4 }}
type: Opaque
stringData:
  deterministic-secret: {{ .Values.deterministic.value | quote }}
{{- end }}
